service: laravel-app

provider:
  name: aws
  region: ap-south-1
  runtime: php-83
  environment:
    APP_ENV: production
    APP_KEY: base64:VSVO/UV/3AtywrR+H7NArlO0Oq3DEVk7fDyKvqVw2CM=
    DB_HOST: crossover.proxy.rlwy.net
    DB_DATABASE: railway
    DB_USERNAME: root
    DB_PASSWORD: qxlSYMXedjtzayeDfXHbDWaeWxXXTaHu

functions:
  web:
    handler: public/index.php
    timeout: 28
    layers:
      - ${bref:layer.php-83-fpm}
    events:
      - httpApi: '*'

plugins:
  - ./vendor/bref/bref
